### ISSUE TITLE
It would be good to have a generator

### ISSUE THREAD

**Issue by stevemao** [sindresorhus/appveyor-node#1]
And used by generator-node https://github.com/yeoman/generator-node/issues/66

**Comment by arthurvr** [comment]
Sounds like something people would like, so :+1:.

> And used by generator-node yeoman/generator-node#66

Nah. We're not using appveyor at any yeoman repo at the moment are we?

**Comment by kevva** [comment]
@arthurvr, not to my knowledge, no.

**Comment by stevemao** [comment]
> Nah. We're not using appveyor at any yeoman repo at the moment are we?

@arthurvr , I know. I've never used it either (too hard to configure and I'm not using windows). But if someone already configured it I would like to try it. As yeoman/generator-node is breaking things into smaller ones so maybe it's not a bad idea to add it.

**Comment by sindresorhus** [comment]
This repo is now archived.
