### ISSUE TITLE
Fsevents issue?

### ISSUE THREAD

**Issue by amilajack** [sindresorhus/appveyor-node#3]
I know this not the best place to ask but I've been looking around for a while now and can't seem to find a solution for fsevents causing appveyor builds to fail.

**Comment by sindresorhus** [comment]
AppVeyor is consistently flaky. I've painfully experienced that too. No solution other than only testing on the latest Node.js version.

**Comment by amilajack** [comment]
I'm testing my project against node 6 and am getting this error:

```
npm ERR! fsevents@1.0.12 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@1.0.12 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fsevents
npm ERR! Or if that isn't available, you can get their
```

Here's the entire log:

https://ci.appveyor.com/project/amilajack/popcorn-time-desktop/build/job/rgyfyp4g5bia4fxw
